## Assignment 2 Data Analysis using Pandas

This assignment will contain 2 question with details as below. The due date is October 23 (Sunday), 2022 23:59PM. Each late day will result in 20% loss of total points.

### Question 1 (20 points) Datacamp courses

Datacamp is the online learning platform for data science courses and modules. As the only collaborator in Portugal, this course provides free access to the students in Business Analytics as the complementary resource. For this assignment, you are expected to complete the following moduels and submit your completion badges:

- [Importing & Cleaning Data with Python](https://app.datacamp.com/learn/skill-tracks/importing-cleaning-data-with-python)
- [Data Manipulation with Python](https://app.datacamp.com/learn/skill-tracks/data-manipulation-with-python)

Each badge will account for 10 points. If you are confident with the knowledge, you may skip the videos and directly finish the challenges. You can submit the badge by the end of the October if you would need more time. 

### Question 2 (80 points) Celluloid ceiling

Wonder Woman             |  Captain Marvel
:-------------------------:|:-------------------------:
![wonderwoman](https://upload.wikimedia.org/wikipedia/en/4/4f/Wonder_Woman_1984_poster.png) | ![marvel](https://upload.wikimedia.org/wikipedia/pt/5/59/Captain_Marvel_%282018%29.jpg)

Women are involved in the film industry in all roles, including as film directors, actresses, cinematographers, film producers, film critics, and other film industry professions, though women have been underrepresented in all these positions. Studies found that women have always had a presence in film acting, but have consistently been underrepresented, and on average significantly less well paid. 

In 2015, Forbes reported that "...just 21 of the 100 top-grossing films of 2014 featured a female lead or co-lead, while only 28.1% of characters in 100 top-grossing films were female... This means it’s much rarer for women to get the sort of blockbuster role which would warrant the massive backend deals many male counterparts demand (Tom Cruise in Mission: Impossible or Robert Downey Jr. in Iron Man, for example)".

Also, Forbes' analysis of US acting salaries in 2013 determined that the "...men on Forbes’ list of top-paid actors for that year made 2½ times as much money as the top-paid actresses. That means that Hollywood's best-compensated actresses made just 40 cents for every dollar that the best-compensated men made. 


In this assignment, we want to examine whether and how women representation is lacking in the film industry. We will adopt The Bechdel test as a measure of the representation of women in the film industry. The test is named after the American cartoonist Alison Bechdel in whose 1985 comic strip Dykes to Watch Out For the test first appeared. **A movie is said to meet the Bechdel test  following three criteria: (1) it has to have at least two women in it, who (2) who talk to each other, about (3) something besides a man.**

We are going to obtain the data ourselves to perform the analysis. Specifically, we will retrieve the movie metadata from IMDB (Internet Movie Database), an online database of information related to films, television programs, home videos, video games, and streaming content online – including cast, production crew and personal biographies, plot summaries, trivia, ratings, and fan and critical reviews. As of January 2020, IMDb has approximately 6.5 million titles (including episodes) and 10.4 million personalities in its database, as well as 83 million registered users.


The IMDb Top 250 is a list of the top rated 250 films, based on ratings by the registered users of the website using the methods described. We will focus on these famous movies in this analysis:

**Question 2.1** (25 points): We will retrieve the metadata of IMDb Top 250 movies from the [IMDb charts](https://www.imdb.com/chart/top/). For each movie on the list, we can scrape the following characteristics from the information page. For example, from the [page of top rated movie "The Shawshank Redemption"](https://www.imdb.com/title/tt0111161/?pf_rd_m=A2FGELUUNOQJNL&pf_rd_p=e31d89dd-322d-4646-8962-327b42fe94b1&pf_rd_r=F4QFC0SVZN1HTDHCY3C0&pf_rd_s=center-1&pf_rd_t=15506&pf_rd_i=top&ref_=chttp_tt_1), we want to extract the metadata about this movie as:
- IMDb id (0111161)
- Movie name (The Shawshank Redemption)
- Year (1994)
- Director (Frank Darabont)
- Stars (Tim Robbins, Morgan Freeman, Bob Gunton)
- Rating (9.3)
- Number of reviews (2.6M)
- Genres (Drama)
- Country (USA)
- Language (English)
- Budget (\$25,000,000)
- Gross box Office Revenue (\$28,884,504)

![imdb](https://mrfloris.com/files/images/imdb-top250-page-start.png)


After scraping the 250 movies, save the data as a dataframe ```imdb_top_movies```. 

Also, saving the dataframe to a local file ```imdb_top_movies.csv``` so that later you can load it without scraping the website twice.

Hint: You can get the links to these movies from the IMDb top chart page, and then scrape each movie page by sending the request to these links. At each movie page, the information requested are located at different sections. 

In [4]:
from requests import get
from bs4 import BeautifulSoup as bs
from time import sleep
from random import randint
import numpy as np, pandas as pd

In [266]:

page = requests.get("https://www.imdb.com/chart/top/")
soup = bs(page.content, 'html.parser')
    
table = soup.find('table')
links = []

# get all rows from the table with the 250 most popular videos and get the href from each movie
row_elements = soup.find_all('td', class_="titleColumn")
for tag inpage = requests.get("https://www.imdb.com/chart/top/")
    row_elements:
    a = tag.find_all('a')
    for argument in a:
        href = argument.get('href')
    links.append(href)
#print(links)

movie_id = []

df = pd.DataFrame(columns=['movie_id', 'title', 'year', 'director', 'star1', 'star2', 'star3', 'runtime', 'rating', 'reviews', 'genre', 'country', 'language', 'budget', 'gross_box_office_rev'])

def get_movie_data(link):
    global df
    for x in link:
        time.sleep(0.01)
        headers = {"Accept-Language": "en-US,en;q=0.5"}
        page = requests.get("https://www.imdb.com" + x, headers=headers)
        soup = bs(page.content, 'html.parser')
        start = '/title/tt'
        movie_idx = (x.split(start))[1]
        movie_idx = movie_idx[:-1]
        movie_id.append(movie_idx)
        titlex = soup.find('h1').text.strip()
        yearx = soup.find('a', class_='ipc-link ipc-link--baseAlt ipc-link--inherit-color sc-8c396aa2-1 WIUyh').text.strip()
        directorx = soup.find('a', class_='ipc-metadata-list-item__list-content-item ipc-metadata-list-item__list-content-item--link').text.strip()
        starx = soup.find_all(class_='sc-bfec09a1-1 gfeYgX')
        stars = []
        for tag in starx:
            star_ = tag.text.strip()
            stars.append(star_)
        star1 = stars[0]
        star2 = stars[1]
        star3 = stars[2]
        runtime = (soup.find(attrs={'data-testid':'title-techspec_runtime'}).div.text.strip().split('|')[0]).split('(')[0]
        ratingx = soup.find('span', class_='sc-7ab21ed2-1 jGRxWM').text.strip()
        number_reviewsx = soup.find('div', class_='sc-7ab21ed2-3 dPVcnq').text.strip()
        genreaux = (soup.find(attrs={'class':'ipc-chip-list__scroller'}).get_text(strip=True).split('|')[0]).split('(')[0]
        genrex = re.findall('[a-zA-Z][^A-Z]*', genreaux)
        countryaux = (soup.find(attrs={'data-testid':'title-details-origin'}).div.text.strip().split('|')[0]).split('(')[0]
        countryx = re.findall('[a-zA-Z][^A-Z]*', countryaux)
        languagesaux = (soup.find(attrs= {"data-testid":"title-details-languages"}).div.get_text(strip=True).split('|')[0]).split('(')[0]
        languagex = re.findall('[a-zA-Z][^A-Z]*', languagesaux)
        try: 
            budgetaux = soup.find(attrs={'data-testid':'title-boxoffice-budget'}).div.text.strip()
            budgetx = budgetaux.split('(')[0]
        except: 
            budgetx = int(0)
        try:
            gross_box_office_revx = soup.find(attrs={'data-testid':'title-boxoffice-cumulativeworldwidegross'}).div.text.strip()
            #gross_box_office_rev.append(gross_box_office_rev)
        except: 
            gross_box_office_revx = int(0)
            
        df = df.append({'movie_id': movie_idx, 'title': titlex, 'year': yearx, 'director': directorx, 'star1': star1, 'star2': star2, 'star3': star3, 'runtime': runtime, 'rating': ratingx, 'reviews': number_reviewsx, 'genre': genrex, 'country': countryx, 'language': languagex, 'budget': budgetx, 'gross_box_office_rev': gross_box_office_revx}, ignore_index=True)
    
get_movie_data(links)

df.to_csv(f'result.csv', index=False)

/var/folders/rn/3x_7sghd7tj02r1tcxcbpxmw0000gn/T/ipykernel_21172/2256855115.py:70: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append({'movie_id': movie_idx, 'title': titlex, 'year': yearx, 'director': directorx, 'star1': star1, 'star2': star2, 'star3': star3, 'runtime': runtime, 'rating': ratingx, 'reviews': number_reviewsx, 'genre': genrex, 'country': countryx, 'language': languagex, 'budget': budgetx, 'gross_box_office_rev': gross_box_office_revx}, ignore_index=True)
/var/folders/rn/3x_7sghd7tj02r1tcxcbpxmw0000gn/T/ipykernel_21172/2256855115.py:70: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append({'movie_id': movie_idx, 'title': titlex, 'year': yearx, 'director': directorx, 'star1': star1, 'star2': star2, 'star3': star3, 'runtime': runtime, 'rating': ratingx, 'reviews': number_reviewsx,

/var/folders/rn/3x_7sghd7tj02r1tcxcbpxmw0000gn/T/ipykernel_21172/2256855115.py:70: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append({'movie_id': movie_idx, 'title': titlex, 'year': yearx, 'director': directorx, 'star1': star1, 'star2': star2, 'star3': star3, 'runtime': runtime, 'rating': ratingx, 'reviews': number_reviewsx, 'genre': genrex, 'country': countryx, 'language': languagex, 'budget': budgetx, 'gross_box_office_rev': gross_box_office_revx}, ignore_index=True)
/var/folders/rn/3x_7sghd7tj02r1tcxcbpxmw0000gn/T/ipykernel_21172/2256855115.py:70: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append({'movie_id': movie_idx, 'title': titlex, 'year': yearx, 'director': directorx, 'star1': star1, 'star2': star2, 'star3': star3, 'runtime': runtime, 'rating': ratingx, 'reviews': number_reviewsx,

/var/folders/rn/3x_7sghd7tj02r1tcxcbpxmw0000gn/T/ipykernel_21172/2256855115.py:70: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append({'movie_id': movie_idx, 'title': titlex, 'year': yearx, 'director': directorx, 'star1': star1, 'star2': star2, 'star3': star3, 'runtime': runtime, 'rating': ratingx, 'reviews': number_reviewsx, 'genre': genrex, 'country': countryx, 'language': languagex, 'budget': budgetx, 'gross_box_office_rev': gross_box_office_revx}, ignore_index=True)
/var/folders/rn/3x_7sghd7tj02r1tcxcbpxmw0000gn/T/ipykernel_21172/2256855115.py:70: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append({'movie_id': movie_idx, 'title': titlex, 'year': yearx, 'director': directorx, 'star1': star1, 'star2': star2, 'star3': star3, 'runtime': runtime, 'rating': ratingx, 'reviews': number_reviewsx,

/var/folders/rn/3x_7sghd7tj02r1tcxcbpxmw0000gn/T/ipykernel_21172/2256855115.py:70: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append({'movie_id': movie_idx, 'title': titlex, 'year': yearx, 'director': directorx, 'star1': star1, 'star2': star2, 'star3': star3, 'runtime': runtime, 'rating': ratingx, 'reviews': number_reviewsx, 'genre': genrex, 'country': countryx, 'language': languagex, 'budget': budgetx, 'gross_box_office_rev': gross_box_office_revx}, ignore_index=True)
/var/folders/rn/3x_7sghd7tj02r1tcxcbpxmw0000gn/T/ipykernel_21172/2256855115.py:70: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append({'movie_id': movie_idx, 'title': titlex, 'year': yearx, 'director': directorx, 'star1': star1, 'star2': star2, 'star3': star3, 'runtime': runtime, 'rating': ratingx, 'reviews': number_reviewsx,

/var/folders/rn/3x_7sghd7tj02r1tcxcbpxmw0000gn/T/ipykernel_21172/2256855115.py:70: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append({'movie_id': movie_idx, 'title': titlex, 'year': yearx, 'director': directorx, 'star1': star1, 'star2': star2, 'star3': star3, 'runtime': runtime, 'rating': ratingx, 'reviews': number_reviewsx, 'genre': genrex, 'country': countryx, 'language': languagex, 'budget': budgetx, 'gross_box_office_rev': gross_box_office_revx}, ignore_index=True)
/var/folders/rn/3x_7sghd7tj02r1tcxcbpxmw0000gn/T/ipykernel_21172/2256855115.py:70: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append({'movie_id': movie_idx, 'title': titlex, 'year': yearx, 'director': directorx, 'star1': star1, 'star2': star2, 'star3': star3, 'runtime': runtime, 'rating': ratingx, 'reviews': number_reviewsx,

/var/folders/rn/3x_7sghd7tj02r1tcxcbpxmw0000gn/T/ipykernel_21172/2256855115.py:70: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append({'movie_id': movie_idx, 'title': titlex, 'year': yearx, 'director': directorx, 'star1': star1, 'star2': star2, 'star3': star3, 'runtime': runtime, 'rating': ratingx, 'reviews': number_reviewsx, 'genre': genrex, 'country': countryx, 'language': languagex, 'budget': budgetx, 'gross_box_office_rev': gross_box_office_revx}, ignore_index=True)
/var/folders/rn/3x_7sghd7tj02r1tcxcbpxmw0000gn/T/ipykernel_21172/2256855115.py:70: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append({'movie_id': movie_idx, 'title': titlex, 'year': yearx, 'director': directorx, 'star1': star1, 'star2': star2, 'star3': star3, 'runtime': runtime, 'rating': ratingx, 'reviews': number_reviewsx,

/var/folders/rn/3x_7sghd7tj02r1tcxcbpxmw0000gn/T/ipykernel_21172/2256855115.py:70: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append({'movie_id': movie_idx, 'title': titlex, 'year': yearx, 'director': directorx, 'star1': star1, 'star2': star2, 'star3': star3, 'runtime': runtime, 'rating': ratingx, 'reviews': number_reviewsx, 'genre': genrex, 'country': countryx, 'language': languagex, 'budget': budgetx, 'gross_box_office_rev': gross_box_office_revx}, ignore_index=True)
/var/folders/rn/3x_7sghd7tj02r1tcxcbpxmw0000gn/T/ipykernel_21172/2256855115.py:70: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append({'movie_id': movie_idx, 'title': titlex, 'year': yearx, 'director': directorx, 'star1': star1, 'star2': star2, 'star3': star3, 'runtime': runtime, 'rating': ratingx, 'reviews': number_reviewsx,

/var/folders/rn/3x_7sghd7tj02r1tcxcbpxmw0000gn/T/ipykernel_21172/2256855115.py:70: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append({'movie_id': movie_idx, 'title': titlex, 'year': yearx, 'director': directorx, 'star1': star1, 'star2': star2, 'star3': star3, 'runtime': runtime, 'rating': ratingx, 'reviews': number_reviewsx, 'genre': genrex, 'country': countryx, 'language': languagex, 'budget': budgetx, 'gross_box_office_rev': gross_box_office_revx}, ignore_index=True)
/var/folders/rn/3x_7sghd7tj02r1tcxcbpxmw0000gn/T/ipykernel_21172/2256855115.py:70: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append({'movie_id': movie_idx, 'title': titlex, 'year': yearx, 'director': directorx, 'star1': star1, 'star2': star2, 'star3': star3, 'runtime': runtime, 'rating': ratingx, 'reviews': number_reviewsx,

/var/folders/rn/3x_7sghd7tj02r1tcxcbpxmw0000gn/T/ipykernel_21172/2256855115.py:70: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append({'movie_id': movie_idx, 'title': titlex, 'year': yearx, 'director': directorx, 'star1': star1, 'star2': star2, 'star3': star3, 'runtime': runtime, 'rating': ratingx, 'reviews': number_reviewsx, 'genre': genrex, 'country': countryx, 'language': languagex, 'budget': budgetx, 'gross_box_office_rev': gross_box_office_revx}, ignore_index=True)
/var/folders/rn/3x_7sghd7tj02r1tcxcbpxmw0000gn/T/ipykernel_21172/2256855115.py:70: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append({'movie_id': movie_idx, 'title': titlex, 'year': yearx, 'director': directorx, 'star1': star1, 'star2': star2, 'star3': star3, 'runtime': runtime, 'rating': ratingx, 'reviews': number_reviewsx,

/var/folders/rn/3x_7sghd7tj02r1tcxcbpxmw0000gn/T/ipykernel_21172/2256855115.py:70: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append({'movie_id': movie_idx, 'title': titlex, 'year': yearx, 'director': directorx, 'star1': star1, 'star2': star2, 'star3': star3, 'runtime': runtime, 'rating': ratingx, 'reviews': number_reviewsx, 'genre': genrex, 'country': countryx, 'language': languagex, 'budget': budgetx, 'gross_box_office_rev': gross_box_office_revx}, ignore_index=True)
/var/folders/rn/3x_7sghd7tj02r1tcxcbpxmw0000gn/T/ipykernel_21172/2256855115.py:70: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append({'movie_id': movie_idx, 'title': titlex, 'year': yearx, 'director': directorx, 'star1': star1, 'star2': star2, 'star3': star3, 'runtime': runtime, 'rating': ratingx, 'reviews': number_reviewsx,

/var/folders/rn/3x_7sghd7tj02r1tcxcbpxmw0000gn/T/ipykernel_21172/2256855115.py:70: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append({'movie_id': movie_idx, 'title': titlex, 'year': yearx, 'director': directorx, 'star1': star1, 'star2': star2, 'star3': star3, 'runtime': runtime, 'rating': ratingx, 'reviews': number_reviewsx, 'genre': genrex, 'country': countryx, 'language': languagex, 'budget': budgetx, 'gross_box_office_rev': gross_box_office_revx}, ignore_index=True)
/var/folders/rn/3x_7sghd7tj02r1tcxcbpxmw0000gn/T/ipykernel_21172/2256855115.py:70: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append({'movie_id': movie_idx, 'title': titlex, 'year': yearx, 'director': directorx, 'star1': star1, 'star2': star2, 'star3': star3, 'runtime': runtime, 'rating': ratingx, 'reviews': number_reviewsx,

/var/folders/rn/3x_7sghd7tj02r1tcxcbpxmw0000gn/T/ipykernel_21172/2256855115.py:70: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append({'movie_id': movie_idx, 'title': titlex, 'year': yearx, 'director': directorx, 'star1': star1, 'star2': star2, 'star3': star3, 'runtime': runtime, 'rating': ratingx, 'reviews': number_reviewsx, 'genre': genrex, 'country': countryx, 'language': languagex, 'budget': budgetx, 'gross_box_office_rev': gross_box_office_revx}, ignore_index=True)
/var/folders/rn/3x_7sghd7tj02r1tcxcbpxmw0000gn/T/ipykernel_21172/2256855115.py:70: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append({'movie_id': movie_idx, 'title': titlex, 'year': yearx, 'director': directorx, 'star1': star1, 'star2': star2, 'star3': star3, 'runtime': runtime, 'rating': ratingx, 'reviews': number_reviewsx,

/var/folders/rn/3x_7sghd7tj02r1tcxcbpxmw0000gn/T/ipykernel_21172/2256855115.py:70: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append({'movie_id': movie_idx, 'title': titlex, 'year': yearx, 'director': directorx, 'star1': star1, 'star2': star2, 'star3': star3, 'runtime': runtime, 'rating': ratingx, 'reviews': number_reviewsx, 'genre': genrex, 'country': countryx, 'language': languagex, 'budget': budgetx, 'gross_box_office_rev': gross_box_office_revx}, ignore_index=True)
/var/folders/rn/3x_7sghd7tj02r1tcxcbpxmw0000gn/T/ipykernel_21172/2256855115.py:70: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append({'movie_id': movie_idx, 'title': titlex, 'year': yearx, 'director': directorx, 'star1': star1, 'star2': star2, 'star3': star3, 'runtime': runtime, 'rating': ratingx, 'reviews': number_reviewsx,

/var/folders/rn/3x_7sghd7tj02r1tcxcbpxmw0000gn/T/ipykernel_21172/2256855115.py:70: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append({'movie_id': movie_idx, 'title': titlex, 'year': yearx, 'director': directorx, 'star1': star1, 'star2': star2, 'star3': star3, 'runtime': runtime, 'rating': ratingx, 'reviews': number_reviewsx, 'genre': genrex, 'country': countryx, 'language': languagex, 'budget': budgetx, 'gross_box_office_rev': gross_box_office_revx}, ignore_index=True)
/var/folders/rn/3x_7sghd7tj02r1tcxcbpxmw0000gn/T/ipykernel_21172/2256855115.py:70: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append({'movie_id': movie_idx, 'title': titlex, 'year': yearx, 'director': directorx, 'star1': star1, 'star2': star2, 'star3': star3, 'runtime': runtime, 'rating': ratingx, 'reviews': number_reviewsx,

/var/folders/rn/3x_7sghd7tj02r1tcxcbpxmw0000gn/T/ipykernel_21172/2256855115.py:70: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append({'movie_id': movie_idx, 'title': titlex, 'year': yearx, 'director': directorx, 'star1': star1, 'star2': star2, 'star3': star3, 'runtime': runtime, 'rating': ratingx, 'reviews': number_reviewsx, 'genre': genrex, 'country': countryx, 'language': languagex, 'budget': budgetx, 'gross_box_office_rev': gross_box_office_revx}, ignore_index=True)
/var/folders/rn/3x_7sghd7tj02r1tcxcbpxmw0000gn/T/ipykernel_21172/2256855115.py:70: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append({'movie_id': movie_idx, 'title': titlex, 'year': yearx, 'director': directorx, 'star1': star1, 'star2': star2, 'star3': star3, 'runtime': runtime, 'rating': ratingx, 'reviews': number_reviewsx,

/var/folders/rn/3x_7sghd7tj02r1tcxcbpxmw0000gn/T/ipykernel_21172/2256855115.py:70: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append({'movie_id': movie_idx, 'title': titlex, 'year': yearx, 'director': directorx, 'star1': star1, 'star2': star2, 'star3': star3, 'runtime': runtime, 'rating': ratingx, 'reviews': number_reviewsx, 'genre': genrex, 'country': countryx, 'language': languagex, 'budget': budgetx, 'gross_box_office_rev': gross_box_office_revx}, ignore_index=True)
/var/folders/rn/3x_7sghd7tj02r1tcxcbpxmw0000gn/T/ipykernel_21172/2256855115.py:70: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append({'movie_id': movie_idx, 'title': titlex, 'year': yearx, 'director': directorx, 'star1': star1, 'star2': star2, 'star3': star3, 'runtime': runtime, 'rating': ratingx, 'reviews': number_reviewsx,

/var/folders/rn/3x_7sghd7tj02r1tcxcbpxmw0000gn/T/ipykernel_21172/2256855115.py:70: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append({'movie_id': movie_idx, 'title': titlex, 'year': yearx, 'director': directorx, 'star1': star1, 'star2': star2, 'star3': star3, 'runtime': runtime, 'rating': ratingx, 'reviews': number_reviewsx, 'genre': genrex, 'country': countryx, 'language': languagex, 'budget': budgetx, 'gross_box_office_rev': gross_box_office_revx}, ignore_index=True)
/var/folders/rn/3x_7sghd7tj02r1tcxcbpxmw0000gn/T/ipykernel_21172/2256855115.py:70: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append({'movie_id': movie_idx, 'title': titlex, 'year': yearx, 'director': directorx, 'star1': star1, 'star2': star2, 'star3': star3, 'runtime': runtime, 'rating': ratingx, 'reviews': number_reviewsx,

In [56]:
# load csv into dataframe
df = pd.read_csv('result.csv', dtype={"movie_id":"string"})
df

movie_id                     title  year              director  \
0    0111161  The Shawshank Redemption  1994        Frank Darabont   
1    0068646             The Godfather  1972  Francis Ford Coppola   
2    0468569           The Dark Knight  2008     Christopher Nolan   
3    0071562     The Godfather Part II  1974  Francis Ford Coppola   
4    0050083              12 Angry Men  1957          Sidney Lumet   
..       ...                       ...   ...                   ...   
245  0071411               Dersu Uzala  1975        Akira Kurosawa   
246  0083987                    Gandhi  1982  Richard Attenborough   
247  1454029                  The Help  2011           Tate Taylor   
248  0103639                   Aladdin  1992          Ron Clements   
249  0129167            The Iron Giant  1999             Brad Bird   

              star1              star2              star3             runtime  \
0       Tim Robbins     Morgan Freeman         Bob Gunton  2 hours 22 minutes   
1     Marlon Brando          Al Pacino         James Caan  2 hours 55 minutes   
2    Christian Bale       Heath Ledger      Aaron Eckhart  2 hours 32 minutes   
3         Al Pacino     Robert De Niro      Robert Duvall  3 hours 22 minutes   
4       Henry Fonda        Lee J. Cobb      Martin Balsam   1 hour 36 minutes   
..              ...                ...                ...                 ...   
245   Maksim Munzuk      Yuriy Solomin    Mikhail Bychkov  2 hours 22 minutes   
246    Ben Kingsley       John Gielgud  Rohini Hattangadi  3 hours 11 minutes   
247     Viola Davis         Emma Stone    Octavia Spencer  2 hours 26 minutes   
248   Scott Weinger     Robin Williams       Linda Larkin   1 hour 30 minutes   
249  Eli Marienthal  Harry Connick Jr.   Jennifer Aniston   1 hour 26 minutes   

     rating reviews                                 genre  \
0       9.3    2.7M                             ['Drama']   
1       9.2    1.8M                    ['Crime', 'Drama']   
2       9.0    2.6M          ['Action', 'Crime', 'Drama']   
3       9.0    1.3M                    ['Crime', 'Drama']   
4       9.0    783K                    ['Crime', 'Drama']   
..      ...     ...                                   ...   
245     8.2     30K   ['Adventure', 'Biography', 'Drama']   
246     8.1    232K                ['Biography', 'Drama']   
247     8.1    458K                             ['Drama']   
248     8.0    417K  ['Animation', 'Adventure', 'Comedy']   
249     8.1    196K  ['Animation', 'Action', 'Adventure']   

                                               country  \
0                                ['United ', 'States']   
1                                ['United ', 'States']   
2          ['United ', 'States', 'United ', 'Kingdom']   
3                                ['United ', 'States']   
4                                ['United ', 'States']   
..                                                 ...   
245                      ['Soviet ', 'Union', 'Japan']   
246  ['United ', 'Kingdom', 'India', 'United ', 'St...   
247                     ['United ', 'States', 'India']   
248                              ['United ', 'States']   
249                              ['United ', 'States']   

                                              language         budget  \
0                                          ['English']   $25,000,000    
1                      ['English', 'Italian', 'Latin']    $6,000,000    
2                              ['English', 'Mandarin']  $185,000,000    
3    ['English', 'Italian', 'Spanish', 'Latin', 'Si...   $13,000,000    
4                                          ['English']      $350,000    
..                                                 ...            ...   
245                             ['Russian', 'Chinese']    $4,000,000    
246                               ['English', 'Hindi']   $22,000,000    
247                                        ['English']   $25,000,000    
248                           

**Question 2.2** (5 points) If you group the movies by release years, show the number of movies at each decade in descending order.

In [57]:
from math import floor
years = df[['movie_id', 'year']]
decades = []
for x in years['year']:
    decades.append(floor(int(x) / 10) * 10)
years['decade'] = decades

result = years.groupby('decade').count()
result = result.sort_values('year', ascending=False)
result['year']

/var/folders/rn/3x_7sghd7tj02r1tcxcbpxmw0000gn/T/ipykernel_75684/313829619.py:7: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  years['decade'] = decades


decade
2000    48
2010    43
1990    41
1980    27
1950    23
1970    19
1960    18
1940    12
1930     7
1920     6
2020     6
Name: year, dtype: int64

**Quesion 2.3** (5 points) Show the number of movies by the distribution of runtime at quartile (0-25%, 25-50%, 50-75%, 75-100%).

In [76]:
# get the runtime in minutes for each movie
def get_minutes(runtime):
    """This function transforms the string input of the runtime and returns only the number of minutes"""
    hh = mm = 0
    for x in runtime.split():
        x = x.lower()
        if x.isdigit():
            save = x
        elif x.startswith('hour'):
            hh = int(save)
        elif x.startswith('minute'):
            mm = int(save)
    return (hh*60)+mm

df["runtime_minutes"] = df["runtime"].apply(getMinutes)

# get the quartiles for each movie
df['quartiles'] = pd.qcut(df['runtime_minutes'], 4, labels=['0-25%', '25-50%', '50-75%', '75-100%'])
print(df['quartiles'].value_counts(sort=False))

0-25%      63
25-50%     62
50-75%     63
75-100%    62
Name: quartiles, dtype: int64


**Question 2.4** (5 points) Show the top 10 most popular actor/actresses in terms of number of movies they have starred. 

In [77]:
from collections import Counter
star1 = df['star1'].tolist()
star2 = df['star2'].tolist()
star3 = df['star3'].tolist()
star1.extend(star2)
star1.extend(star3)
c = Counter(star1)
c.most_common(10)

[('Robert De Niro', 9),
 ('Tom Hanks', 6),
 ('Leonardo DiCaprio', 6),
 ('Harrison Ford', 6),
 ('Christian Bale', 5),
 ('Clint Eastwood', 5),
 ('Charles Chaplin', 5),
 ('Al Pacino', 4),
 ('Brad Pitt', 4),
 ('Jack Nicholson', 4)]

**Question 2.5** (5 points) Show the average ratings of movies across the genres and decades.

In [75]:
#genres dont fit (Scifi, Filmnoir)
from ast import literal_eval

df['year'] = df['year'].astype(int)
df['decades'] = df.year//10 * 10
df['rating'] = df['rating'].astype(float)

# write list elements to own rows
ratings = df[['movie_id', 'title', 'genre', 'decades', 'rating']]
ratings['genre'] = ratings['genre'].apply(literal_eval)
ratings = ratings.explode('genre')

# correct wrong genres Sci-Fi and Film-Noir
ratings = ratings[~ratings['genre'].str.contains("Noir")]
ratings['genre'] = ratings['genre'].str.replace('Film-','Film-Noir')
ratings = ratings[~ratings['genre'].str.contains("Sci-")]
ratings.loc[ratings['genre'] == 'Fi', 'genre'] = 'Sci-Fi' 

# group the dataframe by decades and genres and get the mean ratings
ratings_new = ratings.groupby(['decades', 'genre'])['rating'].mean()
ratings_new

/var/folders/rn/3x_7sghd7tj02r1tcxcbpxmw0000gn/T/ipykernel_75684/3197245172.py:11: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ratings['genre'] = ratings['genre'].apply(literal_eval)


decades  genre    
1920     Action       8.200
         Adventure    8.200
         Biography    8.200
         Comedy       8.225
         Drama        8.250
                      ...  
2020     Crime        8.900
         Drama        8.475
         Fantasy      8.300
         History      8.400
         Mystery      8.550
Name: rating, Length: 150, dtype: float64

**Question 2.6** (10 points) Now let's retrieve data from Bechdel Test Movie website [for each movie](https://bechdeltest.com/). You can send the requests to the API: https://bechdeltest.com/api/v1/doc#getMovieByImdbId. For example, for the movie The Shawshank Redemption (the IMDb id: 0111161), you can simply call: http://bechdeltest.com/api/v1/getMovieByImdbId?imdbid=0111161. 

Create a dataframe ```bechdel_imdb_top``` that merge the bechdel test info with the ```imdb_top_movies``` show how many top 250 movies are also in the bechdel test website.

In [567]:
from urllib.request import urlopen
import json

bechdel_imdb_top = df
bechdel_imdb_top
bechdel_df = pd.DataFrame(columns=['title', 'year', 'rating', 'dubious', 'imdbid', 'id', 'submitterid', 'date', 'visible'])

# get the information from bechdel
for x in df['movie_id']: 
    series = pd.read_json('http://bechdeltest.com/api/v1/getMovieByImdbId?imdbid=' + str(x), typ='series')
    bechdel_df = bechdel_df.append(series, ignore_index=True)
    #print(bechdel_df)

# create one df with imdb and bechdel information  
bechdel_imdb_top = pd.merge(bechdel_imdb_top, bechdel_df[['rating', 'id', 'visible', 'imdbid', 'dubious']], left_on='movie_id', right_on='imdbid', how='left')

/var/folders/rn/3x_7sghd7tj02r1tcxcbpxmw0000gn/T/ipykernel_21172/3744210308.py:12: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  bechdel_df = bechdel_df.append(series, ignore_index=True)
/var/folders/rn/3x_7sghd7tj02r1tcxcbpxmw0000gn/T/ipykernel_21172/3744210308.py:12: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  bechdel_df = bechdel_df.append(series, ignore_index=True)
/var/folders/rn/3x_7sghd7tj02r1tcxcbpxmw0000gn/T/ipykernel_21172/3744210308.py:12: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  bechdel_df = bechdel_df.append(series, ignore_index=True)
/var/folders/rn/3x_7sghd7tj02r1tcxcbpxmw0000gn/T/ipykernel_21172/3744210308.py:12: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a

/var/folders/rn/3x_7sghd7tj02r1tcxcbpxmw0000gn/T/ipykernel_21172/3744210308.py:12: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  bechdel_df = bechdel_df.append(series, ignore_index=True)
/var/folders/rn/3x_7sghd7tj02r1tcxcbpxmw0000gn/T/ipykernel_21172/3744210308.py:12: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  bechdel_df = bechdel_df.append(series, ignore_index=True)
/var/folders/rn/3x_7sghd7tj02r1tcxcbpxmw0000gn/T/ipykernel_21172/3744210308.py:12: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  bechdel_df = bechdel_df.append(series, ignore_index=True)
/var/folders/rn/3x_7sghd7tj02r1tcxcbpxmw0000gn/T/ipykernel_21172/3744210308.py:12: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a

/var/folders/rn/3x_7sghd7tj02r1tcxcbpxmw0000gn/T/ipykernel_21172/3744210308.py:12: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  bechdel_df = bechdel_df.append(series, ignore_index=True)
/var/folders/rn/3x_7sghd7tj02r1tcxcbpxmw0000gn/T/ipykernel_21172/3744210308.py:12: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  bechdel_df = bechdel_df.append(series, ignore_index=True)
/var/folders/rn/3x_7sghd7tj02r1tcxcbpxmw0000gn/T/ipykernel_21172/3744210308.py:12: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  bechdel_df = bechdel_df.append(series, ignore_index=True)
/var/folders/rn/3x_7sghd7tj02r1tcxcbpxmw0000gn/T/ipykernel_21172/3744210308.py:12: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a

/var/folders/rn/3x_7sghd7tj02r1tcxcbpxmw0000gn/T/ipykernel_21172/3744210308.py:12: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  bechdel_df = bechdel_df.append(series, ignore_index=True)
/var/folders/rn/3x_7sghd7tj02r1tcxcbpxmw0000gn/T/ipykernel_21172/3744210308.py:12: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  bechdel_df = bechdel_df.append(series, ignore_index=True)
/var/folders/rn/3x_7sghd7tj02r1tcxcbpxmw0000gn/T/ipykernel_21172/3744210308.py:12: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  bechdel_df = bechdel_df.append(series, ignore_index=True)
/var/folders/rn/3x_7sghd7tj02r1tcxcbpxmw0000gn/T/ipykernel_21172/3744210308.py:12: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a

/var/folders/rn/3x_7sghd7tj02r1tcxcbpxmw0000gn/T/ipykernel_21172/3744210308.py:12: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  bechdel_df = bechdel_df.append(series, ignore_index=True)
/var/folders/rn/3x_7sghd7tj02r1tcxcbpxmw0000gn/T/ipykernel_21172/3744210308.py:12: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  bechdel_df = bechdel_df.append(series, ignore_index=True)
/var/folders/rn/3x_7sghd7tj02r1tcxcbpxmw0000gn/T/ipykernel_21172/3744210308.py:12: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  bechdel_df = bechdel_df.append(series, ignore_index=True)
/var/folders/rn/3x_7sghd7tj02r1tcxcbpxmw0000gn/T/ipykernel_21172/3744210308.py:12: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a

/var/folders/rn/3x_7sghd7tj02r1tcxcbpxmw0000gn/T/ipykernel_21172/3744210308.py:12: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  bechdel_df = bechdel_df.append(series, ignore_index=True)
/var/folders/rn/3x_7sghd7tj02r1tcxcbpxmw0000gn/T/ipykernel_21172/3744210308.py:12: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  bechdel_df = bechdel_df.append(series, ignore_index=True)
/var/folders/rn/3x_7sghd7tj02r1tcxcbpxmw0000gn/T/ipykernel_21172/3744210308.py:12: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  bechdel_df = bechdel_df.append(series, ignore_index=True)
/var/folders/rn/3x_7sghd7tj02r1tcxcbpxmw0000gn/T/ipykernel_21172/3744210308.py:12: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a

/var/folders/rn/3x_7sghd7tj02r1tcxcbpxmw0000gn/T/ipykernel_21172/3744210308.py:12: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  bechdel_df = bechdel_df.append(series, ignore_index=True)
/var/folders/rn/3x_7sghd7tj02r1tcxcbpxmw0000gn/T/ipykernel_21172/3744210308.py:12: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  bechdel_df = bechdel_df.append(series, ignore_index=True)
/var/folders/rn/3x_7sghd7tj02r1tcxcbpxmw0000gn/T/ipykernel_21172/3744210308.py:12: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  bechdel_df = bechdel_df.append(series, ignore_index=True)
/var/folders/rn/3x_7sghd7tj02r1tcxcbpxmw0000gn/T/ipykernel_21172/3744210308.py:12: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a

/var/folders/rn/3x_7sghd7tj02r1tcxcbpxmw0000gn/T/ipykernel_21172/3744210308.py:12: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  bechdel_df = bechdel_df.append(series, ignore_index=True)
/var/folders/rn/3x_7sghd7tj02r1tcxcbpxmw0000gn/T/ipykernel_21172/3744210308.py:12: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  bechdel_df = bechdel_df.append(series, ignore_index=True)
/var/folders/rn/3x_7sghd7tj02r1tcxcbpxmw0000gn/T/ipykernel_21172/3744210308.py:12: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  bechdel_df = bechdel_df.append(series, ignore_index=True)
/var/folders/rn/3x_7sghd7tj02r1tcxcbpxmw0000gn/T/ipykernel_21172/3744210308.py:12: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a

/var/folders/rn/3x_7sghd7tj02r1tcxcbpxmw0000gn/T/ipykernel_21172/3744210308.py:12: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  bechdel_df = bechdel_df.append(series, ignore_index=True)
/var/folders/rn/3x_7sghd7tj02r1tcxcbpxmw0000gn/T/ipykernel_21172/3744210308.py:12: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  bechdel_df = bechdel_df.append(series, ignore_index=True)
/var/folders/rn/3x_7sghd7tj02r1tcxcbpxmw0000gn/T/ipykernel_21172/3744210308.py:12: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  bechdel_df = bechdel_df.append(series, ignore_index=True)
/var/folders/rn/3x_7sghd7tj02r1tcxcbpxmw0000gn/T/ipykernel_21172/3744210308.py:12: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a

In [79]:
# load the bechdel movies from csv
bechdel_imdb_top = pd.read_csv('result_bechdel.csv', dtype={"movie_id":"string"})

# show many movies of Bechdel are not included in Top 250
not_included = bechdel_imdb_top['imdbid'].isna().sum()
print(not_included, 'movies of the Bechdel dataset are not included in the top 250 movies')
bechdel_imdb_top.to_csv(f'result_bdechdel.csv', index=False)

9 movies of the Bechdel dataset are not included in the top 250 movies


In [80]:
# Show just the 250 movies that are included in the Bechdel data
bechdel_imdb_top=bechdel_imdb_top.dropna(subset=['imdbid'])
bechdel_imdb_top

movie_id                     title  year              director  \
0    0111161  The Shawshank Redemption  1994        Frank Darabont   
1    0068646             The Godfather  1972  Francis Ford Coppola   
2    0468569           The Dark Knight  2008     Christopher Nolan   
3    0071562     The Godfather Part II  1974  Francis Ford Coppola   
4    0050083              12 Angry Men  1957          Sidney Lumet   
..       ...                       ...   ...                   ...   
245  0071411               Dersu Uzala  1975        Akira Kurosawa   
246  0083987                    Gandhi  1982  Richard Attenborough   
247  1454029                  The Help  2011           Tate Taylor   
248  0103639                   Aladdin  1992          Ron Clements   
249  0129167            The Iron Giant  1999             Brad Bird   

              star1              star2              star3             runtime  \
0       Tim Robbins     Morgan Freeman         Bob Gunton  2 hours 22 minutes   
1     Marlon Brando          Al Pacino         James Caan  2 hours 55 minutes   
2    Christian Bale       Heath Ledger      Aaron Eckhart  2 hours 32 minutes   
3         Al Pacino     Robert De Niro      Robert Duvall  3 hours 22 minutes   
4       Henry Fonda        Lee J. Cobb      Martin Balsam   1 hour 36 minutes   
..              ...                ...                ...                 ...   
245   Maksim Munzuk      Yuriy Solomin    Mikhail Bychkov  2 hours 22 minutes   
246    Ben Kingsley       John Gielgud  Rohini Hattangadi  3 hours 11 minutes   
247     Viola Davis         Emma Stone    Octavia Spencer  2 hours 26 minutes   
248   Scott Weinger     Robin Williams       Linda Larkin   1 hour 30 minutes   
249  Eli Marienthal  Harry Connick Jr.   Jennifer Aniston   1 hour 26 minutes   

     rating_x reviews  ...                                           language  \
0         9.3    2.7M  ...                                        ['English']   
1         9.2    1.8M  ...                    ['English', 'Italian', 'Latin']   
2         9.0    2.6M  ...                            ['English', 'Mandarin']   
3         9.0    1.3M  ...  ['English', 'Italian', 'Spanish', 'Latin', 'Si...   
4         9.0    783K  ...                                        ['English']   
..        ...     ...  ...                                                ...   
245       8.2     30K  ...                             ['Russian', 'Chinese']   
246       8.1    232K  ...                               ['English', 'Hindi']   
247       8.1    458K  ...                                        ['English']   
248       8.0    417K  ...                                        ['English']   
249       8.1    196K  ...                                        ['English']   

            budget gross_box_office_rev rating_y      id  visible     imdbid  \
0     $25,000,000           $28,884,504      0.0   339.0      1.0   111161.0   
1      $6,000,000          $250,341,816      2.0  2224.0      1.0    68646.0   
2    $185,000,000        $1,006,234,167      3.0    66.0      1.0   468569.0   
3     $13,000,000           $47,961,919      2.0  3896.0      1.0    71562.0   
4        $350,000                  $955      0.0   302.0      1.0    50083.0   
..             ...                  ...      ...     ...      ...        ...   
245    $4,000,000               $14,480      0.0  1807.0      1.0    71411.0   
246   $22,000,000           $52,767,889      2.0  9593.0      1.0    83987.0   
247   $25,000,000          $216,639,112      3.0  2276.0      1.0  1454029.0   
248   $28,000,000          $504,050,219      0.0    98.0      1.0   103639.0   
249   $70,000,000           $23,335,817      0.0   884.0      1.0   129167.0   

     dubious  English                                         genres2  
0        NaN        [                                   ["['Drama']"]  
1        0.0        [                       ["['Crime'", " 'Drama']"]  
2        1.0        [          ["['Actio

**Question 2.7** (5 points) Show the percenage of movies given differen genres that has passed the test in different ways (Number from 0 to 3 (0 means no two women, 1 means no talking, 2 means talking about a man, 3 means it passes the test)) List the top 5 genres that has the highest fail rate (i.e., the movie passes 0 test)

In [81]:
# calculate ways of passing by genre
from ast import literal_eval
bechdel_genre = bechdel_imdb_top
bechdel_genre['genre'] = bechdel_genre['genre'].apply(literal_eval) #convert to list type
bechdel_genre = bechdel_genre.explode("genre")
bechdel_genre = bechdel_genre[["genre", "rating_y", "title"]].copy()
bechdel_genre = bechdel_genre.groupby(["genre", "rating_y"], as_index=False).count() 
bechdel_genre['percentage'] = ((bechdel_genre['title'] / bechdel_genre.groupby(["genre"])["title"].transform("sum")) * 100).round(2)
bechdel_genre

# transform df and show ways of passing test by genre
passing = bechdel_genre.set_index(["genre", "rating_y"])
passing = passing.rename(columns={"title": "Number of Movies"})
passing

Number of Movies  percentage
genre     rating_y                              
Action    0.0                     10       19.61
          1.0                     15       29.41
          2.0                      1        1.96
          3.0                     25       49.02
Adventure 0.0                     13       21.67
...                              ...         ...
War       2.0                      1        4.55
          3.0                      4       18.18
Western   0.0                      2       33.33
          1.0                      3       50.00
          3.0                      1       16.67

[77 rows x 2 columns]

In [82]:
failed = bechdel_genre[bechdel_genre['rating_y'] == 0].nlargest(5, 'percentage')[["genre", "title", "percentage"]]
failed

genre  title  percentage
70      War     11       50.00
74  Western      2       33.33
56  Romance      7       30.43
38    Film-      1       25.00
40  History      2       25.00

**Question 2.8** (5 points) Show the top 10 highest-rated English and non-English movies that passed the test completely (rating=3), respectively. 

In [83]:
# assumption: first language is the main language
# keep the first language 
from ast import literal_eval
languages = bechdel_imdb_top
languages['language'] = languages['language'].apply(literal_eval) #convert to list type
languages = languages.explode('language')
languages = languages.drop_duplicates(subset=['movie_id'])
        
# show top 10 english-speaking movies that passed the test
print('English-speaking movies:')
print(languages[(languages['language'] == 'English') & (languages['rating_y'] == 3)][['rating_x', 'title']].sort_values('rating_x', ascending=False).head(10))
# show top 10 non-english-speaking movies that passed the test
print('\n', 'Non-English-speaking movies:')
print(languages[(languages['language'] != 'English') & (languages['rating_y'] == 3)][['rating_x', 'title']].sort_values('rating_x', ascending=False).head(10))

English-speaking movies:
    rating_x                                  title
2        9.0                        The Dark Knight
5        9.0                       Schindler's List
7        8.9                           Pulp Fiction
12       8.8                              Inception
13       8.8  The Lord of the Rings: The Two Towers
15       8.7                             The Matrix
16       8.7                             Goodfellas
25       8.6                           Interstellar
28       8.6             Terminator 2: Judgment Day
21       8.6               The Silence of the Lambs

 Non-English-speaking movies:
     rating_x              title
30        8.6      Spirited Away
49        8.5        City Lights
33        8.5           Parasite
79        8.4  Princess Mononoke
82        8.4         Your Name.
92        8.4          Capernaum
96        8.3                  M
100       8.3             Amélie
113       8.3          Incendies
115       8.3       A Separation


**Question 2.9** (5 points) Creat a new column ROI that measures the return of investment using (box revenue-budget)/budget, and compare the average ROI between movies that passed (rating=3) and failed the test (rating=0), are their ROI different? Explain.

In [84]:
budget_df = bechdel_imdb_top

# drop the columns that do not start with $
budget_df = budget_df[budget_df['budget'].str.startswith('$')]
budget_df = budget_df[budget_df['gross_box_office_rev'].str.startswith('$')]

# remove the $ sign of budget and gross box office revenue columns and change to integer        
budget_df['budget_without_currency'] = budget_df['budget'].str[1:]
budget_df['budget_without_currency'] = budget_df['budget_without_currency'].str.replace(',', '').astype(int)

budget_df['gross_box_office_rev_wc'] = budget_df['gross_box_office_rev'].str[1:]
budget_df['gross_box_office_rev_wc'] = budget_df['gross_box_office_rev_wc'].str.replace(',', '').astype(int)

# create new column for ROI and round the values
budget_df['ROI'] = round((budget_df['gross_box_office_rev_wc']/budget_df['budget_without_currency']), 2)
passed_roi = round((budget_df[budget_df['rating_y'] == 3]['ROI'].mean()), 2)
failed_roi = round((budget_df[budget_df['rating_y'] == 0]['ROI'].mean()), 2)
print('The average ROI of the passed movies is:',passed_roi,'\n','The average ROI of the failed movies is: ', failed_roi)

The average ROI of the passed movies is: 11.22 
 The average ROI of the failed movies is:  6.69


**Explanation:** It can be noticed that the ROI of movies that have passed the Bechdel test is higher than the ROI of movies that havent passed the Bechdel test. So, one can assume that spectators prefer to watch movies with woman and men instead of movies with just men. 

**Question 2.10** (10 points) Now load the bech test results from all movies (https://bechdeltest.com/api/v1/doc#getAllMovies) that contains the all movies that are rated by the Bechdel Test website. Are women representation improved over the decades? Create a dataframe ```bechdel_imdb```, comparing the top 250 and other movies, in terms of percentage, how many passed/failed the test? 

In [85]:
## assumption: as in the tasks before: test failed is defined as receiving 0 and passed reveiving 3
# get all movies from bechdel and remove the movies that are in the top 250
bechdel_imdb = pd.read_json('http://bechdeltest.com/api/v1/getAllMovies')
bechdel_imdb = bechdel_imdb[~bechdel_imdb.imdbid.isin(bechdel_imdb_top.movie_id)]
bechdel_imdb['decades'] = bechdel_imdb.year//10 * 10

# transform rating to a category type
bechdel_imdb["rating"] = bechdel_imdb["rating"].astype("category")

# unstack dataframe
bechdel_imdb_over_years = bechdel_imdb.groupby(["decades", "rating"])["rating"].count()
bechdel_imdb_over_years = bechdel_imdb_over_years.unstack()
bechdel_imdb_over_years

rating     0    1    2     3
decades                     
1870       4    0    0     0
1880      16    0    0     0
1890      64    2    0     1
1900      39    2    1     0
1910      11    0    4    11
1920      31   10   19    17
1930      21   40   41    94
1940      33   48   34   114
1950      35   57   40   138
1960      71   97   39   160
1970      61  116   47   198
1980      86  153   78   345
1990      89  272  113   610
2000     187  502  208  1353
2010     252  669  295  2104
2020      24   53   29   251

In [54]:
per_fail = round((bechdel_imdb[bechdel_imdb["rating"] == 0].shape[0]/bechdel_imdb.shape[0])*100, 2)
per_pass = round((bechdel_imdb[bechdel_imdb["rating"] == 3].shape[0]/bechdel_imdb.shape[0])*100,2)

# get percentages for all movies
print("Out of all movies, {} % of movies failed the test completely (rating 0). {} % of movies passed the test (rating 3).".format(per_fail, per_pass))
all_ratings = bechdel_imdb.groupby("rating")["title"].count().to_frame()
all_ratings["%"] = round(all_ratings["title"] * 100 / all_ratings.sum()[0],2)
print(allGroupedRatings[(all_ratings.index == 0) | (all_ratings.index == 3)])

# get percentages for top 250 movies
per_fail_top = round((bechdel_imdb_top[bechdel_imdb_top["rating_y"] == 0].shape[0]/bechdel_imdb_top.shape[0])*100, 2)
per_pass_top = round((bechdel_imdb_top[bechdel_imdb_top["rating_y"] == 3].shape[0]/bechdel_imdb_top.shape[0])*100,2)

print("\n"+"For the top 250 imdb movies, {} % of movies failed the test completely (raiting 0). {} % of movies passed the test (rating 3).".format(per_fail_top, per_fail_top))
top_ratings = bechdel_imdb_top.groupby("rating_y")["title"].count().to_frame()
top_ratings["%"] = round(top_ratings["title"] * 100 / top_ratings.sum()[0],2)
print(top_ratings[(top_ratings.index == 0) | (top_ratings.index == 3)])

Out of all movies, 10.91 % of movies failed the test completely (rating 0). 57.47 % of movies passed the test (rating 3).
        title      %
rating              
0        1024  10.91
3        5396  57.47

For the top 250 imdb movies, 20.33 % of movies failed the test completely (raiting 0). 20.33 % of movies passed the test (rating 3).
          title      %
rating_y              
0.0          49  20.33
3.0          93  38.59
